statsd:
  url: '172.17.0.2:8125'
  prefix: pong

servers:
  - addr: localhost:5000
    readtimeout: 100s
    writetimeout: 100s
    handlers:
      - id: h1
        path: /
        responses:
            - rate: 100%
              code: 200
              body: ok1
              delay: 0s

  - addr: localhost:5001
    readtimeout: 100s
    writetimeout: 100s
    handlers:
      - id: h2
        path: /
        responses:
            - rate: 50%
              code: 200
              body: ok2
              delay: 0s

            - rate: 50%
              code: 200
              body: ok2-drop
              drop: true
              delay: 0s

  - addr: localhost:5002
    readtimeout: 100s
    writetimeout: 100s
    handlers:
      - id: h2
        path: /
        responses:
            - rate: 10%
              code: 200
              body: ok2
              delay: 0s

            - rate: 90%
              code: 200
              body: ok2
              drop: true
              delay: 0s

  - addr: localhost:5003
    readtimeout: 100s
    writetimeout: 100s
    handlers:
      - id: h2
        path: /
        responses:
            - rate: 10%
              code: 200
              body: ok2
              delay: 0s

            - rate: 90%
              code: 200
              body: ok2
              drop: true
              delay: 0s

  - addr: localhost:5004
    readtimeout: 100s
    writetimeout: 100s
    handlers:
      - id: h2
        path: /
        responses:
            - rate: 10%
              code: 200
              body: ok2
              delay: 0s

            - rate: 90%
              code: 200
              body: ok2
              drop: true
              delay: 0s

logging:
  - name: console
  - name: syslog