statsd:
  url: '172.17.0.2:8125'
  prefix: pong

servers:
  - addr: localhost:5000
    readtimeout: 10s
    writetimeout: 10s
    handlers:
      - id: good
        path: /
        responses:

            - rate: 50%
              code: 200
              body: ok
              delay: 0s

            - rate: 50%
              code: 500
              body: not ok
              drop: true
              delay: 0s200ms

  - addr: localhost:5001
    readtimeout: 10s
    writetimeout: 10s
    handlers:
      - id: bad
        path: /
        responses:

            - rate: 50%
              code: 200
              body: ok
              delay: 0s

            - rate: 50%
              code: 500
              body: not ok
              drop: true
              delay: 0s200ms

logging:
  - name: console
  - name: syslog