servers:
  - addr: localhost:5000
    readtimeout: 10s
    writetimeout: 10s
    handlers:
      /:
        - rate: 50%
          code: 200
          body: ok
          delay: 0s

        - rate: 50%
          code: 500
          body: not ok
          delay: 1s

logging:
  - name: console
  - name: syslog